sudo: required
language: csharp
solution: Valorl.GTLibrary.Api.sln
services:
  - docker
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
      key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
    packages:
    - dotnet-dev-1.0.1
before_install:
  - nvm install node
before_script:
  - chmod +x ./scripts/travis-build-api.sh
  - chmod +x ./scripts/travis-test-api.sh
  # - chmod +x ./scripts/travis-build-app.sh
  # - chmod +x ./scripts/travis-test-app.sh
  - chmod +x ./scripts/after-success.sh
script:
  - cd scripts
  - ./travis-build-api.sh
  - ./travis-test-api.sh
  # - ./travis-build-app.sh
  # - ./travis-test-app.sh
after_success:
  - cd scripts && ./after-success.sh
# deploy:
#   provider: s3
#   access_key_id: ${AWS_ACCESS_KEY_ID}
#   secret_access_key: ${AWS_SECRET_ACCESS_KEY}
#   bucket: "gtl-vueapp-bucket"
#   skip_cleanup: true
#   local_dir: "app/dist"
